// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0rbv_NEY6O7XWJd_5TjszxiuPXnLGIto',
    appId: '1:1078849438390:web:0a4b8a185351df81a05c17',
    messagingSenderId: '1078849438390',
    projectId: 'facebook-36350',
    authDomain: 'facebook-36350.firebaseapp.com',
    storageBucket: 'facebook-36350.firebasestorage.app',
    measurementId: 'G-G6YL9M3T2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAZNQV_poJiLr4dHMBXc6PQeof5uSo6GI',
    appId: '1:1078849438390:android:e434ec4944794925a05c17',
    messagingSenderId: '1078849438390',
    projectId: 'facebook-36350',
    storageBucket: 'facebook-36350.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoxGAHCSPRShvfiiUfKCJfvcS3N5A6nhw',
    appId: '1:1078849438390:ios:0b977e8653eeb07aa05c17',
    messagingSenderId: '1078849438390',
    projectId: 'facebook-36350',
    storageBucket: 'facebook-36350.firebasestorage.app',
    iosClientId: '1078849438390-tobl4qt692ck0855ora25i9k67vtq68i.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoxGAHCSPRShvfiiUfKCJfvcS3N5A6nhw',
    appId: '1:1078849438390:ios:0b977e8653eeb07aa05c17',
    messagingSenderId: '1078849438390',
    projectId: 'facebook-36350',
    storageBucket: 'facebook-36350.firebasestorage.app',
    iosClientId: '1078849438390-tobl4qt692ck0855ora25i9k67vtq68i.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebook',
  );
}
